### ISSUE TITLE
Not supported on tf 0.12

### ISSUE THREAD

**Issue by karthicgit-zz** [kral2/terraform-oci-advanced-vcn#2]
I have changed few lines for supporting tf 0.12. Raised a pull request from karthicgit.

**Comment by kral2** [comment]
PR merged. Thanks.
I made lot of changes to this module since my last commit. Will have to publish them as soon as I can.

Note : I am considering a major rewrite to better handle security lists. Currently, there is too much limitations, it is a bit messy, and it doesn't leverage TF0.12+ enhancements :-(
